services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
        - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongo:27017/mistergold?authSource=admin
    depends_on:
      - mongo
